<?php
/**
 * @Rogier maybe move folder to Admin?
 */
return $fields = [
    [
        'id'       => 'review_notice_shown',
        'type'     => 'hidden',
        'label'    => '',
        'disabled' => false,
        'default'  => false,
    ],
    [
        'id'       => 'tour_shown_once',
        'type'     => 'hidden',
        'label'    => '',
        'default'  => false,
    ],
    [
        'id'       => 'company_name',
        'type'     => 'api',
        'default'  => '',
    ],
	[
		'id'       => 'domain',
		'type'     => 'api',
		'default'  => '',
	],
	[
        'id'       => 'company_id',
        'type'     => 'api',
        'default'  => false,
    ],
	[
		'id'       => 'terms-and-conditions',
		'type'     => 'text',
		'default'  => false,
	],
	[
		'id'       => 'email',
		'type'     => 'text',
		'default'  => '',
	],
	[
		'id'       => 'tips-and-tricks',
		'type'     => 'text',
		'default'  => false,
	],
	[
		'id'       => 'phone',
		'type'     => 'text',
		'default'  => '',
	],
	[
		'id'       => 'address',
		'type'     => 'text',
		'default'  => '',
	],
	[
		'id'       => 'zip',
		'type'     => 'text',
		'default'  => '',
	],
	[
		'id'       => 'category',
		'type'     => 'text',
		'default'  => 0,
	],
	[
		'id'       => 'city',
		'type'     => 'text',
		'default'  => '',
	],
	[
		'id'       => 'country',
		'type'     => 'text',
		'default'  => '',
	],
	[
		'id'       => 'service',
		'type'     => 'text',
		'label'    => __("Service", 'simplybook'),
		'default'  => '',
	],
    [
        'id'       => 'template',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'default'  => 'default',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'server',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'default',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'timeline_type',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'modern',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'datepicker_type',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'top_calendar',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'is_rtl',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => false,
        'widget_field'  => '/',
    ],
    [
        'id'       => 'allow_switch_to_ada',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'switch',
        'label'    => __('Allow switch to ADA', 'simplybook'),
        'disabled' => false,
        'default'  => false,
        'widget_field'  => '/',
    ],
    [
        'id'       => 'clear_session',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'switch',
        'label'    => __('Clear session', 'simplybook'),
        'disabled' => false,
        'default'  => false,
        'widget_field'  => '/',
    ],
    [
        'id'       => 'timeline_modern_display',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'as_slots',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'display_item_mode',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'block',
        'widget_field'  => '/',

    ],
    [
        'id'       => 'primary_color',
        'label'     => __( "Primay color", 'simplybook' ),
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'disabled' => false,
        'default'  => '#DD3649',
        'widget_field'  => '/',
	    'inline_group'    => 'widget',
    ],
    [
        'id'       => 'booking_nav_bg_color',
        'label'     => __( "Background", 'simplybook' ),
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'disabled' => false,
        'default'  => '#DD3649',
        'widget_field'  => '/',
	    'inline_group'    => 'widget',
    ],
    [
        'id'       => 'body_bg_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => __('Body background color', 'simplybook' ),
        'disabled' => false,
        'default'  => '#F2F2F2',
        'widget_field'  => '/',
        'inline_group'    => 'widget',
    ],
	[
        'id'       => 'sb_selected',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => __('Selected color', 'simplybook' ),
        'disabled' => false,
        'default'  => '#F2F2F2',
        'widget_field'  => '/',
        'inline_group'    => 'widget',
    ],
    [
        'id'       => 'dark_font_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => __('Dark font color', 'simplybook' ),
        'disabled' => false,
        'default'  => '#474747',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'light_font_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#F5FCFF',
        'widget_field'  => '/',

    ],
    [
        'id'       => 'btn_color_1',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#DD3649',
        'widget_field'  => '/',

    ],
    [
        'id'       => 'sb_company_label_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#FFFFFF',
        'widget_field'  => '/',

    ],
    [
        'id'       => 'sb_busy',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#c7b3b3',
        'widget_field'  => '/',

    ],
    [
        'id'       => 'sb_available',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#D6EBFF',
        'widget_field'  => '/',

    ],
    [
        'id'       => 'sb_base_color',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#DD3649',
        'widget_field'  => '/',

    ],
    [
        'id'       => 'timeline_show_end_time',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 0,
        'widget_field'  => '/',

    ],
    [
        'id'       => 'timeline_hide_unavailable',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 1,
        'widget_field'  => '/',

    ],
    [
        'id'       => 'hide_past_days',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 0,
        'widget_field'  => '/',

    ],
    [
        'id'       => 'hide_img_mode',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 1,
        'widget_field'  => '/',
    ],
    [
        'id'       => 'show_sidebar',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 1,
        'widget_field'  => '/',
    ],
    [
        'id'       => 'predefined',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 1,
        'widget_field'  => '/',

    ],
];