<?php
/**
 * @Rogier maybe move folder to Admin?
 */
return $fields = [
    [
        'id'       => 'review_notice_shown',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'hidden',
        'label'    => '',
        'disabled' => false,
        'default'  => false,
    ],
    [
        'id'       => 'tour_shown_once',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'hidden',
        'label'    => '',
        'default'  => false,
    ],
    [
        'id'       => 'token',
        'type'     => 'api',
        'encrypt'  => true,
        'label'    => '',
        'default'  => '',
    ],
	[
		'id'       => 'company_token',
		'type'     => 'api',
		'encrypt'  => true,
		'label'    => '',
		'default'  => '',
	],
    [
        'id'       => 'company_name',
        'type'     => 'api',
        'default'  => false,
    ],
	[
        'id'       => 'company_id',
        'type'     => 'api',
        'default'  => false,
    ],
	[
		'id'       => 'terms-and-conditions',
		'type'     => 'text',
		'default'  => false,
	],
	[
		'id'       => 'email',
		'type'     => 'text',
		'default'  => false,
	],
	[
		'id'       => 'phone',
		'type'     => 'text',
		'default'  => false,
	],
	[
		'id'       => 'address',
		'type'     => 'text',
		'default'  => false,
	],
	[
		'id'       => 'expires',
		'type'     => 'api',
		'default'  => false,
	],
	[
		'id'       => 'recaptcha_site_key',
		'type'     => 'api',
		'default'  => false,
	],
	[
		'id'       => 'recaptcha_version',
		'type'     => 'api',
		'default'  => false,
	],
	[
		'id'       => 'company_login',
		'type'     => 'api',
		'default'  => false,
	],
	[
		'id'       => 'zip',
		'type'     => 'text',
		'default'  => false,
	],
	[
		'id'       => 'category',
		'type'     => 'text',
		'default'  => false,
	],
	[
		'id'       => 'city',
		'type'     => 'text',
		'default'  => false,
	],
    [
        'id'       => 'refresh_token',
        'type'     => 'api',
        'encrypt'  => true,
        'default'  => false,
    ],
    [
        'id'       => 'login',
        'type'     => 'api',
        'label'    => '',
        'default'  => is_admin() && is_user_logged_in() ? get_option( 'admin_email' ) : '',
    ],
    [
        'id'       => 'require2fa',
        'type'     => 'api',
        'default'  => false,
    ],
    [
        'id'       => 'allowed2fa_providers',
        'type'     => 'api',
        'default'  => [],
    ],
    [
        'id'       => 'auth_session_id',
        'type'     => 'api',
    ],
    [
        'id'       => 'auth_datetime',
        'type'     => 'api',
    ],
    [
        'id'       => 'is_auth',
        'type'     => 'api',
    ],
    [
        'id'       => 'id',
        'type'     => 'api',
    ],
    [
        'id'       => 'is_refreshed',
        'type'     => 'api',
    ],
    [
        'id'       => 'refresh_time',
        'type'     => 'api',
    ],
    [
        'id'       => 'template',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'default'  => 'default',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'server',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'default',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'timeline_type',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'modern',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'datepicker_type',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'top_calendar',
        'widget_field'  => '/',
    ],
    [
        'id'       => 'is_rtl',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => false,
        'widget_field'  => '/',
    ],
    [
        'id'       => 'allow_switch_to_ada',
        'menu_id'  => 'design',
        'group_id' => 'design',
        'type'     => 'switch',
        'label'    => __('Allow switch to ADA', 'simplybook'),
        'disabled' => false,
        'default'  => false,
        'widget_field'  => '/',
    ],
    [
        'id'       => 'clear_session',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'switch',
        'label'    => __('Clear session', 'simplybook'),
        'disabled' => false,
        'default'  => false,
        'widget_field'  => '/',
    ],
    [
        'id'       => 'timeline_modern_display',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'as_slots',
        'widget_field'  => 'themeparams',
    ],
    [
        'id'       => 'display_item_mode',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 'block',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'booking_nav_bg_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#DD3649',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'body_bg_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#F2F2F2',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'dark_font_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#474747',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'light_font_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#F5FCFF',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'btn_color_1',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#DD3649',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'sb_company_label_color',
        'menu_id'  => 'design',
        'group_id' => 'palettes',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#FFFFFF',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'sb_busy',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#c7b3b3',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'sb_available',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#D6EBFF',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'sb_base_color',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => '#DD3649',
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'timeline_show_end_time',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 0,
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'timeline_hide_unavailable',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 1,
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'hide_past_days',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 0,
        'widget_field'  => 'themeparams',

    ],
    [
        'id'       => 'hide_img_mode',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 1,
        'widget_field'  => 'themeparams',
    ],
    [
        'id'       => 'show_sidebar',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 1,
        'widget_field'  => 'themeparams',
    ],
    [
        'id'       => 'predefined',
        'menu_id'  => 'general',
        'group_id' => 'general',
        'type'     => 'text',
        'label'    => '',
        'disabled' => false,
        'default'  => 1,
        'widget_field'  => '/',

    ],
];