<?php
defined( 'ABSPATH' ) or die( );
return
    [
        'primary_color' => [
            'id'       => 'primary_color',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Primary color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#DD3649',
            'widget_field'  => '/',
            'inline_group' =>  "main",
        ],
        'secondary_color' => [
            'id'       => 'secondary_color',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Secondary color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#DD3649',
            'widget_field'  => '/',
            'inline_group' =>  "main",
        ],
        'sb_base_color' => [
            'id'       => 'sb_base_color',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Base color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#DD3649',
            'widget_field'  => '/',
            'inline_group' =>  "main",
        ],
        'sb_company_label_color' => [
            'id'       => 'sb_company_label_color',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Company label color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#FFFFFF',
            'widget_field'  => '/',
            'inline_group' =>  "main",
        ],
        'sb_hover' => [
            'id'       => 'sb_hover',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Hover color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#FFFFFF',
            'widget_field'  => '/',
            'inline_group' =>  "main",
        ],
        'booking_nav_bg_color' => [
            'id'       => 'booking_nav_bg_color',
            'label'     => __( "Background", 'simplybook' ),
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'disabled' => false,
            'default'  => '#DD3649',
            'widget_field'  => '/',
            'inline_group'    => 'background_colors',
        ],
        'body_bg_color' => [
            'id'       => 'body_bg_color',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Body background color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#F2F2F2',
            'widget_field'  => '/',
            'inline_group'    => 'background_colors',
        ],
        'btn_color_1' => [
            'id'       => 'btn_color_1',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Button color 1', 'simplybook' ),
            'disabled' => false,
            'default'  => '#DD3649',
            'widget_field'  => '/',
            'inline_group' =>  "buttons",
        ],
        'btn_color_2' => [
            'id'       => 'btn_color_2',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Button color 2', 'simplybook' ),
            'disabled' => false,
            'default'  => '#DD3649',
            'widget_field'  => '/',
            'inline_group'    => 'buttons',
        ],
        'sb_busy' => [
            'id'       => 'sb_busy',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Busy color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#c7b3b3',
            'widget_field'  => '/',
            'inline_group'    => 'state',
        ],
        'sb_available' => [
            'id'       => 'sb_available',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Available color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#D6EBFF',
            'widget_field'  => '/',
            'inline_group'    => 'state',
        ],
        'sb_selected' => [
            'id'       => 'sb_selected',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Selected color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#F2F2F2',
            'widget_field'  => '/',
            'inline_group'    => 'state',
        ],
        'dark_font_color' => [
            'id'       => 'dark_font_color',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Dark font color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#474747',
            'widget_field'  => '/',
            'inline_group'    => 'fonts',

        ],
        'light_font_color' => [
            'id'       => 'light_font_color',
            'menu_id'  => 'design',
            'group_id' => 'colors',
            'type'     => 'colorpicker',
            'label'    => __( 'Light font color', 'simplybook' ),
            'disabled' => false,
            'default'  => '#F5FCFF',
            'widget_field'  => '/',
            'inline_group'    => 'fonts',

        ],
];