<?php
defined( 'ABSPATH' ) or die( );

return
	[
		'theme' => [
			'id'       => 'theme',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'label'    => __('Theme', 'simplybook'),
			'options' => [
				'space' => 'Space',
				'creative' => 'Creative',
				'minimal' => 'Minimal',
				'dainty' => 'Dainty',
				'inspiration' => 'Inspiration',
				'air' => 'Air',
				'emeri' => 'Emeri',
				'bookingtroll' => 'Bookingtroll',
				'classic' => 'Classic',
				'hugo' => 'Hugo',
				'belle' => 'Belle',
				'concise' => 'Concise',
				'simple-beauty' => 'Simple Beauty',
				'blur' => 'Blur',
				'skittish' => 'Skittish',
				'tender' => 'Tender',
				'default' => 'Default',
				'ada-compliant' => 'ADA Compliant',
			],
			'default'  => 'default',
			'widget_field'  => '/',
		],

		'timeline_type' => [
			'id'       => 'timeline_type',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'options' => [
				"flexible" => __("Flexible", "simplybook"),
				"modern" => __("Modern", "simplybook"),
				"flexible_week" => __("Flexible weekly", "simplybook"),
				"modern_week" => __("Slots weekly", "simplybook"),
				"classes" => __("Modern Provider", "simplybook"),
				"flexible_provider" => __("Flexible Provider", "simplybook"),
				"grid_week" => __("Weekly classes", "simplybook"),
			],
			'label'    => __('Timeline type', 'simplybook'),
			'disabled' => false,
			'default'  => 'modern',
			'widget_field'  => '/',
		],
		'datepicker' => [
			'id'       => 'datepicker',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'label'    => __('Datepicker type', 'simplybook'),
			'disabled' => false,
			'options' => [
				'inline_datepicker' => __('Inline Datepicker','simplybook'),
				'top_calendar' => __('Top Calendar','simplybook'),
			],
			'default'  => 'top_calendar',
			'widget_field'  => '/',
		],
		'is_rtl' => [
			'id'       => 'is_rtl',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
            'label'    => __('RTL', 'simplybook'),
            'help'     => sprintf(
                __('When selected, writing starts from the right of the page and continues to the left, proceeding from top to bottom for new lines. Your website %s set to RTL.', 'simplybook'),
                (is_rtl() ? 'IS' : 'IS NOT'),
            ),
			'disabled' => false,
			'default'  => is_rtl(),
			'widget_field'  => '/',
		],
		'allow_switch_to_ada' => [
			'id'       => 'allow_switch_to_ada',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Allow switch to ADA', 'simplybook'),
			'disabled' => false,
			'default'  => false,
			'widget_field'  => '/',
		],
		'timeline_modern_display' => [
			'id'       => 'timeline_modern_display',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'label'    => __('Timeline modern display', 'simplybook'),
			'disabled' => false,
			'default'  => 'as_slots',
			'options' => [
				'as_slots' => __('As slots','simplybook'),
				'as_table' => __('As table','simplybook'),
			],
			'widget_field'  => '/',
		],
		'display_item_mode' => [
			'id'       => 'display_item_mode',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'label'    => __('Display item mode', 'simplybook'),
			'disabled' => false,
			'options'  => [
				'block' => __('Block', 'simplybook'),
				'list' => __('List', 'simplybook'),
			],
			'default'  => 'block',
			'widget_field'  => '/',

		],
		'timeline_show_end_time' => [
			'id'       => 'timeline_show_end_time',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Timeline show end time', 'simplybook'),
			'disabled' => false,
			'default'  => 0,
			'widget_field'  => '/',

		],
		'timeline_hide_unavailable' => [
			'id'       => 'timeline_hide_unavailable',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Timeline hide unavailable', 'simplybook'),
			'disabled' => false,
			'default'  => 1,
			'widget_field'  => '/',

		],
		'hide_past_days' => [
			'id'       => 'hide_past_days',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Hide past days', 'simplybook'),
			'disabled' => false,
			'default'  => 0,
			'widget_field'  => '/',

		],
		'show_sidebar' => [
			'id'       => 'show_sidebar',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Show sidebar', 'simplybook'),
			'disabled' => false,
			'default'  => 1,
			'widget_field'  => '/',
		],
	];