<?php
defined( 'ABSPATH' ) or die( );

return
	[
        'timeline_type' => [
            'id'       => 'timeline_type',
            'menu_id'  => 'design',
            'group_id' => 'main',
            'type'     => 'select',
            'options' => [
                "flexible" => __("Flexible", "simplybook"),
                "modern" => __("Modern", "simplybook"),
                "flexible_week" => __("Flexible weekly", "simplybook"),
                "modern_week" => __("Slots weekly", "simplybook"),
                "classes" => __("Modern Provider", "simplybook"),
                "flexible_provider" => __("Flexible Provider", "simplybook"),
                "grid_week" => __("Weekly classes", "simplybook"),
            ],
            'label'    => __('Calendar layout', 'simplybook'),
            'disabled' => false,
            'default'  => 'modern',
            'widget_field'  => '/',
        ],
		'datepicker' => [
			'id'       => 'datepicker',
			'menu_id'  => 'design',
			'group_id' => 'main',
			'type'     => 'select',
			'label'    => __('Datepicker type', 'simplybook'),
			'disabled' => false,
			'options' => [
				'inline_datepicker' => __('Inline Datepicker','simplybook'),
				'top_calendar' => __('Top Calendar','simplybook'),
			],
			'default'  => 'top_calendar',
			'widget_field'  => '/',
		],
		'is_rtl' => [
			'id'       => 'is_rtl',
			'menu_id'  => 'design',
			'group_id' => 'main',
			'type'     => 'checkbox',
            'label'    => __('RTL', 'simplybook'),
            'help'     => sprintf(
                __('When selected, writing starts from the right of the page and continues to the left, proceeding from top to bottom for new lines. Your website %s set to RTL.', 'simplybook'),
                (is_rtl() ? 'IS' : 'IS NOT'),
            ),
			'disabled' => false,
			'default'  => is_rtl(),
			'widget_field'  => '/',
		],
		'allow_switch_to_ada' => [
			'id'       => 'allow_switch_to_ada',
			'menu_id'  => 'design',
			'group_id' => 'main',
			'type'     => 'checkbox',
			'label'    => __('Allow switch to ADA', 'simplybook'),
			'disabled' => false,
			'default'  => false,
			'widget_field'  => '/',
		],
        'clear_session' => [
            'id'       => 'clear_session',
            'menu_id'  => 'design',
            'group_id' => 'main',
            'type'     => 'checkbox',
            'label'    => __('Clear the session of each widget initialization', 'simplybook'),
            'disabled' => false,
            'default'  => 0,
            'widget_field'  => '/',
        ],
        'reviews_count' => [
            'id'       => 'reviews_count',
            'menu_id'  => 'design',
            'group_id' => 'reviews',
            'type'     => 'checkbox',
            'label'    => __('Add the reviews count', 'simplybook'),
            'default'  => true,
            'widget_field'  => '/',
        ],
        'hide_add_reviews' => [
            'id'       => 'hide_add_reviews',
            'menu_id'  => 'design',
            'group_id' => 'reviews',
            'type'     => 'checkbox',
            'label'    => __('Hide the add reviews button', 'simplybook'),
            'default'  => true,
            'widget_field'  => '/',
        ],
        'button_title' => [
            'id'       => 'button_title',
            'menu_id'  => 'design',
            'group_id' => 'booking',
            'type'     => 'text',
            'label'    => __('Booking button title', 'simplybook'),
            'default'  => __("Book now", 'simplybook'),
            'widget_field'  => '/',
        ],
	];