<?php
defined( 'ABSPATH' ) or die( );

add_filter( 'simplybook_fields', function( $fields ) {
	return array_merge( $fields,
		[
			[
				'id'       => 'template',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'text',
				'label'    => '',
				'default'  => 'default',
				'widget_field'  => '/',
			],

			[
				'id'       => 'timeline_type',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'text',
				'label'    => '',
				'disabled' => false,
				'default'  => 'modern',
				'widget_field'  => '/',
			],
			[
				'id'       => 'datepicker_type',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'text',
				'label'    => '',
				'disabled' => false,
				'default'  => 'top_calendar',
				'widget_field'  => '/',
			],
			[
				'id'       => 'is_rtl',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'hidden',
				'label'    => '',
				'disabled' => false,
				'default'  => false,
				'widget_field'  => '/',
			],
			[
				'id'       => 'allow_switch_to_ada',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'checkbox',
				'label'    => __('Allow switch to ADA', 'simplybook'),
				'disabled' => false,
				'default'  => false,
				'widget_field'  => '/',
			],
			[
				'id'       => 'timeline_modern_display',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'text',
				'label'    => __('Timeline modern display', 'simplybook'),
				'disabled' => false,
				'default'  => 'as_slots',
				'widget_field'  => '/',
			],
			[
				'id'       => 'display_item_mode',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'text',
				'label'    => '',
				'disabled' => false,
				'default'  => 'block',
				'widget_field'  => '/',

			],
			[
				'id'       => 'timeline_show_end_time',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'checkbox',
				'label'    => '',
				'disabled' => false,
				'default'  => 0,
				'widget_field'  => '/',

			],
			[
				'id'       => 'timeline_hide_unavailable',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'checkbox',
				'label'    => '',
				'disabled' => false,
				'default'  => 1,
				'widget_field'  => '/',

			],
			[
				'id'       => 'hide_past_days',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'checkbox',
				'label'    => '',
				'disabled' => false,
				'default'  => 0,
				'widget_field'  => '/',

			],
			[
				'id'       => 'hide_img_mode',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'checkbox',
				'label'    => '',
				'disabled' => false,
				'default'  => 1,
				'widget_field'  => '/',
			],
			[
				'id'       => 'show_sidebar',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'checkbox',
				'label'    => '',
				'disabled' => false,
				'default'  => 1,
				'widget_field'  => '/',
			],
			[
				'id'       => 'predefined',
				'menu_id'  => 'design',
				'group_id' => 'design',
				'type'     => 'text',
				'label'    => '',
				'disabled' => false,
				'default'  => 1,
				'widget_field'  => '/',

			],
		]
	);
}, 300 );