<?php
defined( 'ABSPATH' ) or die( );

return
	[
		[
			'id'       => 'theme',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'label'    => __('Theme', 'simplybook'),
			'options' => [
				'space' => 'Space',
				'creative' => 'Creative',
				'minimal' => 'Minimal',
				'dainty' => 'Dainty',
				'inspiration' => 'Inspiration',
				'air' => 'Air',
				'emeri' => 'Emeri',
				'bookingtroll' => 'Bookingtroll',
				'classic' => 'Classic',
				'hugo' => 'Hugo',
				'belle' => 'Belle',
				'concise' => 'Concise',
				'simple-beauty' => 'Simple Beauty',
				'blur' => 'Blur',
				'skittish' => 'Skittish',
				'tender' => 'Tender',
				'default' => 'Default',
				'ada-compliant' => 'ADA Compliant',
			],
			'default'  => 'default',
			'widget_field'  => '/',
		],

		[
			'id'       => 'timeline_type',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'text',
			'label'    => __('Timeline type', 'simplybook'),
			'disabled' => false,
			'default'  => 'modern',
			'widget_field'  => '/',
		],
		[
			'id'       => 'datepicker',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'label'    => __('Datepicker type', 'simplybook'),
			'disabled' => false,
			'options' => [
				'inline_datepicker' => __('Inline Datepicker','simplybook'),
				'top_calendar' => __('Top Calendar','simplybook'),
			],
			'default'  => 'top_calendar',
			'widget_field'  => '/',
		],
		[
			'id'       => 'is_rtl',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'hidden',
			'label'    => '',
			'disabled' => false,
			'default'  => false,
			'widget_field'  => '/',
		],
		[
			'id'       => 'allow_switch_to_ada',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Allow switch to ADA', 'simplybook'),
			'disabled' => false,
			'default'  => false,
			'widget_field'  => '/',
		],
		[
			'id'       => 'timeline_modern_display',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'label'    => __('Timeline modern display', 'simplybook'),
			'disabled' => false,
			'default'  => 'as_slots',
			'options' => [
				'as_slots' => __('As slots','simplybook'),
				'as_table' => __('As table','simplybook'),
			],
			'widget_field'  => '/',
		],
		[
			'id'       => 'display_item_mode',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'select',
			'label'    => __('Display item mode', 'simplybook'),
			'disabled' => false,
			'options'  => [
				'block' => __('Block', 'simplybook'),
				'list' => __('List', 'simplybook'),
			],
			'default'  => 'block',
			'widget_field'  => '/',

		],
		[
			'id'       => 'timeline_show_end_time',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Timeline show end time', 'simplybook'),
			'disabled' => false,
			'default'  => 0,
			'widget_field'  => '/',

		],
		[
			'id'       => 'timeline_hide_unavailable',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Timeline hide unavailable', 'simplybook'),
			'disabled' => false,
			'default'  => 1,
			'widget_field'  => '/',

		],
		[
			'id'       => 'hide_past_days',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Hide past days', 'simplybook'),
			'disabled' => false,
			'default'  => 0,
			'widget_field'  => '/',

		],
		[
			'id'       => 'show_sidebar',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'checkbox',
			'label'    => __('Show sidebar', 'simplybook'),
			'disabled' => false,
			'default'  => 1,
			'widget_field'  => '/',
		],
		[
			'id'       => 'predefined',
			'menu_id'  => 'design',
			'group_id' => 'design',
			'type'     => 'text',
			'label'    => __('Predefined', 'simplybook'),
			'disabled' => false,
			'default'  => 1,
			'widget_field'  => '/',

		],
	];