<?php
defined( 'ABSPATH' ) or die( );
return
	[
		[
			'id'       => 'palette',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'palettes',
			'label'    => __( 'Palettes', 'simplybook' ),
			'disabled' => false,
			'default'  => 'persian',
			'options'  => [
				[
					'id' => 'persian',
					'label' => __( 'Persian', 'simplybook' ),
					'colors' => [ '#2E1A47', '#FFFFFF', '#333333', '#B07D50', '#FFFFFF' ],
				],
				[
					'id' => 'france',
					'label' => __( 'France', 'simplybook' ),
					'colors' => [ '#2E5BB6', '#FFFFFF', '#0D1635', '#D04950', '#FFFFFF' ],
				],
				[
					'id' => 'bee',
					'label' => __( 'Bee', 'simplybook' ),
					'colors' => [ '#D9A441', '#FFFFFF', '#333333', '#333333', '#FFFFFF' ],
				],
				[
					'id' => 'custom',
					'label' => __( 'Custom', 'simplybook' ),
					'colors' => [ '#D9A441', '#FFFFFF', '#333333', '#333333', '#FFFFFF' ],
				],
			],

			'widget_field'  => '/',
		],
		[
			'id'       => 'sb_base_color',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Base color', 'simplybook' ),
			'disabled' => false,
			'default'  => '#DD3649',
			'widget_field'  => '/',
			'inline_group' =>  "main",
		],
		[
			'id'       => 'btn_color_1',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Button color 1', 'simplybook' ),
			'disabled' => false,
			'default'  => '#DD3649',
			'widget_field'  => '/',
			'inline_group' =>  "main",

		],
		[
			'id'       => 'sb_company_label_color',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Company label color', 'simplybook' ),
			'disabled' => false,
			'default'  => '#FFFFFF',
			'widget_field'  => '/',
			'inline_group' =>  "main",
		],
		[
			'id'       => 'booking_nav_bg_color',
			'label'     => __( "Background", 'simplybook' ),
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'disabled' => false,
			'default'  => '#DD3649',
			'widget_field'  => '/',
			'inline_group'    => 'background_colors',
		],
		[
			'id'       => 'body_bg_color',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Body background color', 'simplybook' ),
			'disabled' => false,
			'default'  => '#F2F2F2',
			'widget_field'  => '/',
			'inline_group'    => 'background_colors',
		],
		[
			'id'       => 'btn_color_2',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Button color 2', 'simplybook' ),
			'disabled' => false,
			'default'  => '#DD3649',
			'widget_field'  => '/',
			'inline_group'    => 'buttons',

		],
		[
			'id'       => 'sb_busy',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Busy color', 'simplybook' ),
			'disabled' => false,
			'default'  => '#c7b3b3',
			'widget_field'  => '/',
			'inline_group'    => 'buttons',

		],
		[
			'id'       => 'sb_available',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Available color', 'simplybook' ),
			'disabled' => false,
			'default'  => '#D6EBFF',
			'widget_field'  => '/',
			'inline_group'    => 'buttons',


		],
		[
			'id'       => 'sb_selected',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Selected color', 'simplybook' ),
			'disabled' => false,
			'default'  => '#F2F2F2',
			'widget_field'  => '/',
			'inline_group'    => 'buttons',
		],
		[
			'id'       => 'dark_font_color',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Dark font color', 'simplybook' ),
			'disabled' => false,
			'default'  => '#474747',
			'widget_field'  => '/',
			'inline_group'    => 'fonts',

		],
		[
			'id'       => 'light_font_color',
			'menu_id'  => 'design',
			'group_id' => 'palettes',
			'type'     => 'colorpicker',
			'label'    => __( 'Light font color', 'simplybook' ),
			'disabled' => false,
			'default'  => '#F5FCFF',
			'widget_field'  => '/',
			'inline_group'    => 'fonts',

		],


	];